
import { IconDefinition } from '@fortawesome/angular-fontawesome';
import { faAirbnb} from '@fortawesome/free-brands-svg-icons';
import {
  faBan,
  faBars,
  faBox,
  faChampagneGlasses,
  faChessRook,
  faCircle,
  faCircleNotch,
  faDollarSign,
  faEarthEurope,
  faExclamation,
  faEye,
  faFire,
  faHillRockslide,
  faHouse, faKitchenSet, faLightbulb, faMinus, faMugSaucer, faPersonSkiing, faPlus, faSailboat,
  faSearch, faSnowflake, faTent, faTowerObservation, faTractor, faTrashCan, faTree, faUmbrellaBeach,
  faUser, faWater
} from '@fortawesome/free-solid-svg-icons';

export const fontAwsomeIcons: IconDefinition[] = [
  faBan,
  faBars,
  faBox,
  faChampagneGlasses,
  faChessRook,
  faCircle,
  faCircleNotch,
  faDollarSign,
  faEarthEurope,
  faExclamation,
  faEye,
  faFire,
  faHillRockslide,
  faHouse,
  faKitchenSet,
  faLightbulb,
  faMinus,
  faMugSaucer,
  faPersonSkiing,
  faPlus,
  faSailboat,
  faSearch,
  faSnowflake,
  faTent,
  faTowerObservation,
  faTractor,
  faTrashCan,
  faTree,
  faUmbrellaBeach,
  faUser,
  faWater,
  faAirbnb,
  faCircleNotch
]
