version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: velora_postgres_backend
    environment:
      POSTGRES_USER: velora
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: velora
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - velora_network

volumes:
  postgres_data:

networks:
  velora_network:
    driver: bridge
